export const GAME_OPTIONS = [

  // 🔫 SHOOTERS / COMPETITIVOS
  "Valorant",
  "Counter-Strike 2",
  "Call of Duty: Warzone",
  "Call of Duty: Black Ops III",
  "Call of Duty: Modern Warfare",
  "Call of Duty: Modern Warfare II",
  "Call of Duty: Modern Warfare III",
  "Apex Legends",
  "Fortnite",
  "Rainbow Six Siege",
  "Overwatch 2",
  "Paladins",
  "Splitgate",
  "The Finals",
  "PUBG: Battlegrounds",
  "Escape from Tarkov",
  "Battlefield 2042",
  "Battlefield V",
  "Battlefield 1",
  "Halo Infinite",
  "Halo: The Master Chief Collection",
  "Insurgency: Sandstorm",
  "Squad",
  "Hell Let Loose",
  "Ready or Not",
  "XDefiant",

  // 👻 COOP / HORROR / PARTY
  "Lethal Company",
  "Phasmophobia",
  "Among Us",
  "Pummel Party",
  "Party Animals",
  "Move or Die",
  "Human: Fall Flat",
  "Gang Beasts",
  "Goose Goose Duck",
  "Devour",
  "Forewarned",
  "Inside the Backrooms",
  "Escape the Backrooms",
  "Pacify",
  "Ghost Exile",
  "Lunch Lady",
  "Content Warning",

  // 🧱 SANDBOX / SUPERVIVENCIA
  "Minecraft",
  "Terraria",
  "Valheim",
  "Project Zomboid",
  "Don't Starve Together",
  "ARK: Survival Evolved",
  "ARK: Survival Ascended",
  "Rust",
  "The Forest",
  "Sons of the Forest",
  "7 Days to Die",
  "Green Hell",
  "Core Keeper",
  "Enshrouded",
  "V Rising",
  "Grounded",
  "Icarus",
  "Conan Exiles",

  // ⚔️ MMO / ONLINE GRANDES
  "World of Warcraft",
  "Lost Ark",
  "Albion Online",
  "Black Desert Online",
  "New World",
  "Final Fantasy XIV",
  "Guild Wars 2",
  "The Elder Scrolls Online",
  "Runescape",
  "Old School Runescape",

  // 🚗 DEPORTES / CASUAL / COMPETITIVO
  "Rocket League",
  "EA Sports FC 24",
  "FIFA 23",
  "eFootball",
  "NBA 2K24",
  "Golf It",
  "Super BATTLE GOLF",
  "Kopanito All-Stars Soccer",
  "WWE 2K24",
  "Tony Hawk's Pro Skater 1+2",

  // 🧠 ESTRATEGIA / RTS
  "Age of Empires II",
  "Age of Empires IV",
  "Age of Empires III",
  "Company of Heroes 2",
  "Stronghold Crusader HD",
  "Civilization VI",
  "Northgard",
  "Total War: Warhammer III",
  "StarCraft II",
  "Warcraft III",

  // ⚔️ ACCIÓN COOP
  "Warframe",
  "Destiny 2",
  "Borderlands 2",
  "Borderlands 3",
  "Deep Rock Galactic",
  "Helldivers 2",
  "Monster Hunter: World",
  "Monster Hunter Rise",
  "Payday 2",
  "Payday 3",
  "Killing Floor 2",
  "Vermintide 2",
  "Remnant: From the Ashes",
  "Remnant 2",
  "Outriders",
  "Risk of Rain 2",

  // 🧙‍♂️ RPG COOP
  "Baldur's Gate 3",
  "Divinity: Original Sin 2",
  "Diablo IV",
  "Path of Exile",
  "Path of Exile 2",
  "Torchlight II",
  "Torchlight III",
  "Grim Dawn",
  "Warhammer 40K: Inquisitor Martyr",

  // 🚜 SIMULACIÓN / RELAJADO
  "Euro Truck Simulator 2",
  "American Truck Simulator",
  "Farming Simulator 22",
  "PowerWash Simulator",
  "Microsoft Flight Simulator (multiplayer)",
  "Bus Simulator 21",

  // 🧱 CONSTRUCCIÓN / MANAGEMENT COOP
  "Satisfactory",
  "Factorio",
  "Hydroneer",
  "Astroneer",
  "Eco",
  "Captain of Industry",

  // 🎮 INDIE MULTIPLAYER
  "Cuphead (Coop)",
  "Unrailed",
  "Overcooked",
  "Overcooked 2",
  "PlateUp!",
  "Tools Up!",
  "Heave Ho",
  "SpeedRunners",
  "Castle Crashers",
  "BattleBlock Theater",

  // 🧟 ZOMBIES / ACCIÓN
  "Left 4 Dead 2",
  "Back 4 Blood",
  "World War Z",
  "Dying Light (Coop)",
  "Dying Light 2",
  "Dead Island 2",
  "No More Room in Hell",

  // 🧭 AVENTURA COOP
  "Sea of Thieves",
  "Raft",
  "We Were Here",
  "We Were Here Too",
  "We Were Here Forever",
  "It Takes Two",
  "A Way Out",

  // 🧪 EXPERIMENTALES / CAÓTICOS
  "Ultimate Chicken Horse",
  "Totally Accurate Battle Simulator",
  "Totally Reliable Delivery Service",
  "Clustertruck (multiplayer mods)",
  "Stick Fight: The Game",
  "Rounds",
  "Duck Game",

  // 🎯 OTROS POPULARES
  "Fall Guys",
  "Brawlhalla",
  "MultiVersus",
  "Trackmania",
  "Quake Champions",
  "Smite",
  "League of Legends",
  "Dota 2",
  "Teamfight Tactics",
  "Dead by Daylight",
  "Hunt: Showdown",
  "War Thunder",
  "Crossout",

];